### PR TITLE
Plugin's new methods

### PR DESCRIPTION
**Pull request by alexandresgf**
Added new methods to the plugin
- submitScoreNow
- getPlayerScore
- unlockAchievementNow
- incrementAchievementNow

### CODE REVIEW

**Comment by Script47** [comment]
@alexandresgf Do you still update this plugin on your fork?

**Comment by alexandresgf** [comment]
Not anymore... but still works in my game! So, I believe that it can be used.

**Comment by Script47** [comment]
Thanks for the speedy response, yeah I noticed, this might be asking a lot but is there any chance of you maintaining this plugin? It's the only active one I can find with good features.

**Comment by alexandresgf** [comment]
For real?! It isn't asked a lot! Lol! You're the first one. So, yes... as I'm a hybrid mobile game developer, everytime I need something in this plugin, I just got back and write some new lines. Today, it still works, and has a lot of features, at least the basic ones... and eventually I will update with my necessities. But, if you have something specific in mind, please, open an issue in my fork! :D

**Comment by Script47** [comment]
Awesome! I get to writing feature requests, much appreciated.

**Comment by RenaudROHLINGER** [comment]
Could it be possible to add features like Saved Game Service ? (https://developers.google.com/games/services/common/concepts/savedgames)

I am not the best in java but I could try if you don't have the utility to develop it.

**Pull request merged**
